name: Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Setup yarn
      run: npm install -g yarn
      
    - name: Install dependencies
      run: yarn install
      
    - name: Running lint
      run: yarn lint

    - name: Running tests
      run: yarn test
    
    - name: Building project
      run: yarn build

  deploy: 
    
    needs: tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Setup yarn
      run: npm install -g yarn
      
    - name: Install dependencies
      run: yarn install
    
    - name: Building project
      run: yarn build